version: '3.8'

services:
  mongodb-database:
    container_name: restaurants-db
    image: mongo:6.0.6
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoDev
      - MONGO_INITDB_ROOT_PASSWORD=Passw0rd
      - MONGO_INITDB_DATABASE=restaurants
    volumes:
      - dev-db:/data/db

networks:
  nesjs-network:

volumes:
  dev-db: